# encoding: utf-8
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models

class Migration(SchemaMigration):

    def forwards(self, orm):
        
        # Adding model 'Row'
        db.create_table('census_row', (
            ('id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('fileid', self.gf('django.db.models.fields.CharField')(max_length=6, db_index=True)),
            ('filetype', self.gf('django.db.models.fields.CharField')(db_index=True, max_length=6, null=True, blank=True)),
            ('stusab', self.gf('django.db.models.fields.CharField')(max_length=2, db_index=True)),
            ('chariter', self.gf('django.db.models.fields.CharField')(max_length=3, db_index=True)),
            ('cifsn', self.gf('django.db.models.fields.CharField')(max_length=4, db_index=True)),
            ('logrecno', self.gf('django.db.models.fields.CharField')(max_length=7, db_index=True)),
            ('col1', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col2', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col3', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col4', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col5', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col6', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col7', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col8', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col9', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col10', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col11', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col12', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col13', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col14', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col15', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col16', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col17', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col18', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col19', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col20', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col21', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col22', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col23', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col24', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col25', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col26', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col27', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col28', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col29', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col30', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col31', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col32', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col33', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col34', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col35', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col36', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col37', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col38', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col39', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col40', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col41', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col42', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col43', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col44', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col45', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col46', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col47', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col48', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col49', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col50', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col51', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col52', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col53', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col54', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col55', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col56', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col57', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col58', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col59', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col60', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col61', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col62', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col63', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col64', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col65', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col66', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col67', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col68', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col69', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col70', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col71', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col72', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col73', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col74', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col75', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col76', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col77', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col78', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col79', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col80', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col81', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col82', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col83', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col84', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col85', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col86', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col87', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col88', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col89', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col90', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col91', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col92', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col93', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col94', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col95', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col96', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col97', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col98', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col99', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col100', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col101', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col102', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col103', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col104', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col105', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col106', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col107', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col108', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col109', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col110', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col111', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col112', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col113', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col114', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col115', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col116', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col117', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col118', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col119', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col120', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col121', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col122', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col123', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col124', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col125', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col126', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col127', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col128', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col129', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col130', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col131', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col132', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col133', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col134', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col135', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col136', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col137', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col138', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col139', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col140', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col141', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col142', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col143', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col144', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col145', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col146', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col147', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col148', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col149', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col150', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col151', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col152', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col153', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col154', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col155', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col156', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col157', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col158', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col159', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col160', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col161', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col162', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col163', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col164', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col165', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col166', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col167', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col168', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col169', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col170', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col171', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col172', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col173', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col174', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col175', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col176', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col177', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col178', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col179', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col180', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col181', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col182', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col183', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col184', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col185', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col186', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col187', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col188', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col189', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col190', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col191', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col192', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col193', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col194', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col195', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col196', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col197', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col198', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col199', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col200', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col201', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col202', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col203', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col204', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col205', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col206', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col207', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col208', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col209', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col210', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col211', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col212', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col213', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col214', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col215', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col216', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col217', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col218', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col219', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col220', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col221', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col222', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col223', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col224', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col225', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col226', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col227', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col228', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col229', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col230', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col231', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col232', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col233', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col234', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col235', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col236', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col237', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col238', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col239', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col240', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col241', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col242', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col243', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col244', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col245', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col246', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col247', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col248', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col249', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col250', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col251', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col252', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col253', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col254', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col255', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('col256', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
        ))
        db.send_create_signal('census', ['Row'])


    def backwards(self, orm):
        
        # Deleting model 'Row'
        db.delete_table('census_row')


    models = {
        'census.row': {
            'Meta': {'object_name': 'Row'},
            'chariter': ('django.db.models.fields.CharField', [], {'max_length': '3', 'db_index': 'True'}),
            'cifsn': ('django.db.models.fields.CharField', [], {'max_length': '4', 'db_index': 'True'}),
            'col1': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col10': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col100': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col101': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col102': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col103': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col104': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col105': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col106': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col107': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col108': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col109': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col11': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col110': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col111': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col112': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col113': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col114': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col115': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col116': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col117': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col118': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col119': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col12': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col120': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col121': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col122': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col123': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col124': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col125': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col126': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col127': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col128': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col129': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col13': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col130': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col131': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col132': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col133': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col134': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col135': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col136': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col137': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col138': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col139': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col14': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col140': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col141': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col142': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col143': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col144': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col145': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col146': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col147': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col148': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col149': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col15': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col150': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col151': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col152': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col153': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col154': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col155': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col156': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col157': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col158': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col159': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col16': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col160': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col161': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col162': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col163': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col164': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col165': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col166': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col167': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col168': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col169': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col17': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col170': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col171': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col172': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col173': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col174': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col175': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col176': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col177': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col178': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col179': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col18': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col180': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col181': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col182': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col183': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col184': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col185': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col186': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col187': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col188': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col189': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col19': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col190': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col191': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col192': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col193': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col194': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col195': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col196': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col197': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col198': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col199': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col2': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col20': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col200': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col201': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col202': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col203': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col204': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col205': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col206': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col207': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col208': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col209': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col21': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col210': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col211': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col212': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col213': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col214': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col215': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col216': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col217': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col218': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col219': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col22': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col220': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col221': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col222': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col223': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col224': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col225': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col226': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col227': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col228': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col229': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col23': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col230': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col231': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col232': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col233': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col234': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col235': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col236': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col237': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col238': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col239': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col24': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col240': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col241': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col242': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col243': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col244': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col245': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col246': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col247': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col248': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col249': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col25': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col250': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col251': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col252': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col253': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col254': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col255': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col256': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col26': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col27': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col28': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col29': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col3': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col30': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col31': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col32': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col33': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col34': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col35': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col36': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col37': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col38': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col39': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col4': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col40': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col41': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col42': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col43': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col44': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col45': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col46': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col47': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col48': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col49': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col5': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col50': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col51': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col52': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col53': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col54': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col55': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col56': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col57': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col58': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col59': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col6': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col60': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col61': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col62': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col63': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col64': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col65': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col66': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col67': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col68': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col69': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col7': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col70': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col71': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col72': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col73': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col74': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col75': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col76': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col77': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col78': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col79': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col8': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col80': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col81': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col82': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col83': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col84': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col85': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col86': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col87': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col88': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col89': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col9': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col90': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col91': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col92': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col93': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col94': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col95': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col96': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col97': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col98': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'col99': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'fileid': ('django.db.models.fields.CharField', [], {'max_length': '6', 'db_index': 'True'}),
            'filetype': ('django.db.models.fields.CharField', [], {'db_index': 'True', 'max_length': '6', 'null': 'True', 'blank': 'True'}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'logrecno': ('django.db.models.fields.CharField', [], {'max_length': '7', 'db_index': 'True'}),
            'stusab': ('django.db.models.fields.CharField', [], {'max_length': '2', 'db_index': 'True'})
        }
    }

    complete_apps = ['census']
